package calculadora;


/**
 * Esta clase permite definir una calculadora básica que puede realizar
 * 4 operaciones básicas: suma, resta, multiplicación y división
 * @author miguel
 *
 */

public class calculadora2 { 
	private static int num1; // variable entera para introducir el primer operando
	private static int num2; // variable entera para introducir el segundo operando
	

	/**
	 * Constructor que asigna los parámetros a los operandos.
	 * @param a - Valor a asignar al primer operando
	 * @param b - Valor a asignar al segundo operando
	 */
	public calculadora2(int a, int b) {
		/*
		 * Este constructor asignará el parámetro a al primer operador
		 * y el parámetro b al segundo operador para reallizar
		 * la operación correspondiente.
		 */
		num1=a;
		num2=b;
	}

	
	/**
	 * Método que permite sumar dos números enteros y devolver el resultado
	 * @return devuelve la suma del primer operando con el segundo operando
	 */
	public static int suma() {
	int resultado=num1+num2;
	return resultado;
	}
	
	/**
	 * Método que permite restar dos números enteros y devolver el resultado
	 * @return devuelve la resta del primer operando menos el segundo operando
	 */
	public int resta() {
		int resultado=num1-num2;
		return resultado;
		}
	/**
	 * Método que permite multiplicar dos números enteros y devolver el resultado
	 * @return devuelve la multiplicación del primer operando con el segundo operando
	 */	
	public int multiplica() {
		int resultado=num1*num2;
		return resultado;
		}
	/**
	 * Método que permite dividir dos números enteros y devolver el resultado
	 * @return devuelve la división del primer operando entre el segundo operando
	 */
	public int divide() {
		int resultado=num1/num2;
		return resultado;
		}
		
		
	
	/**
	 * Función principal del sistema.
	 * @param args
	 */
	public static void main(String[] args) {
		// TODO Autogenerated method stub
		calculadora2 cal =new calculadora2 (3,4);
		System.out.println(suma());
		
	}

}
